version: "3.3"

services:
  frontend:
    volumes:
      - .:/usr/src/app
    build: ./
    ports:
      - 3000:3000 # host:container
    restart: always
    environment:
      - VIRTUAL_HOST=seattle.test
      - VIRTUAL_PORT=3000
      - apiEndpoint=https://api.seattle.net/

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend

volumes:
  db_data: {}
